name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # 10분마다 실행

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server
        run: curl -s https://blog-factory-engine.onrender.com/ping
